#!/usr/bin/env python3
"""
Generate PRD.md from requirements.yaml

This script reads the machine-readable requirements.yaml and generates
a human-readable PRD.md file. This ensures single source of truth.

Usage:
    python scripts/generate_prd.py
"""

import yaml
from pathlib import Path


def generate_prd(yaml_path: Path, output_path: Path):
    """Generate PRD.md from requirements.yaml"""
    
    # Read YAML
    with open(yaml_path, 'r') as f:
        data = yaml.safe_load(f)
    
    # Start building Markdown
    lines = [
        "<!-- AUTO-GENERATED from requirements.yaml -->",
        "<!-- Do not edit this file directly. Edit requirements.yaml and run: python scripts/generate_prd.py -->",
        "",
        "# Product Requirement Document (PRD)",
        "",
        "## Overview",
        "InferScope is a single-GPU/single-node AI inference bottleneck analysis tool that provides end-to-end timeline visibility and actionable optimization suggestions.",
        "",
        "## Functional Requirements",
        ""
    ]
    
    # Add functional requirements
    frs = data.get('functional_requirements', {})
    for fr_id in sorted(frs.keys()):
        fr = frs[fr_id]
        lines.append(f"### {fr_id}: {fr['title']}")
        lines.append(f"- **Description**: {fr['description']}")
        lines.append("- **Acceptance Criteria**: ")
        for criterion in fr.get('acceptance_criteria', []):
            lines.append(f"  - {criterion}")
        lines.append("")
    
    # Add non-functional requirements
    lines.append("## Non-Functional Requirements")
    lines.append("")
    
    nfrs = data.get('non_functional_requirements', {})
    for nfr_id in sorted(nfrs.keys()):
        nfr = nfrs[nfr_id]
        lines.append(f"### {nfr_id}: {nfr['title']}")
        lines.append(f"- **Description**: {nfr['description']}")
        
        # Handle different NFR structures
        if 'metric' in nfr:
            lines.append(f"- **Acceptance Criteria**: {nfr['metric']}")
        elif 'constraint' in nfr:
            lines.append(f"- **Acceptance Criteria**: {nfr['constraint']}")
        elif 'scope' in nfr:
            lines.append(f"- **Acceptance Criteria**: {nfr['scope']}")
        elif 'platforms' in nfr:
            lines.append("- **Acceptance Criteria**: Tested on " + ", ".join(nfr['platforms']))
        
        lines.append("")
    
    # Add out-of-scope section
    lines.extend([
        "## Out-of-Scope",
        "- Model accuracy or algorithm optimization",
        "- Multi-GPU or distributed inference",
        "- Manual kernel tuning or compilation",
        "- Benchmark rankings or comparisons",
        "- Windows or macOS support (MVP)",
    ])
    
    # Write to file
    output_path.write_text('\n'.join(lines) + '\n')
    print(f"✓ Generated {output_path} from {yaml_path}")


if __name__ == '__main__':
    # Paths relative to repository root
    repo_root = Path(__file__).parent.parent
    yaml_path = repo_root / 'Doc' / '1_requirements' / 'requirements.yaml'
    output_path = repo_root / 'Doc' / '1_requirements' / 'PRD.md'
    
    if not yaml_path.exists():
        print(f"Error: {yaml_path} not found")
        exit(1)
    
    generate_prd(yaml_path, output_path)
