#!/usr/bin/env python3
"""
Generate ICD.md from interfaces.yaml

This script reads the machine-readable interfaces.yaml and generates
a human-readable ICD.md (Interface Control Document) file.

Usage:
    python scripts/generate_icd.py
"""

import yaml
from pathlib import Path


def generate_icd(yaml_path: Path, output_path: Path):
    """Generate ICD.md from interfaces.yaml"""
    
    # Read YAML
    with open(yaml_path, 'r') as f:
        data = yaml.safe_load(f)
    
    # Start building Markdown
    lines = [
        "<!-- AUTO-GENERATED from interfaces.yaml -->",
        "<!-- Do not edit this file directly. Edit interfaces.yaml and run: python scripts/generate_icd.py -->",
        "",
        "# Interface Control Document (ICD)",
        "",
        "## Overview",
        "This document defines all inter-module APIs, data formats, and communication contracts for InferScope.",
        "",
    ]
    
    # Python API Section
    if 'python_api' in data:
        lines.extend([
            "## Python API (User-Facing)",
            ""
        ])
        
        for i, (api_name, api_spec) in enumerate(data['python_api'].items(), 1):
            lines.append(f"### {api_name}()")
            lines.append("")
            lines.append(f"**Description:** {api_spec['description']}")
            lines.append("")
            
            # Signature
            lines.append("**Signature:**")
            lines.append("```python")
            lines.append(api_spec['signature'])
            lines.append("```")
            lines.append("")
            
            # Methods (if present)
            if 'methods' in api_spec:
                lines.append("**Methods:**")
                for method in api_spec['methods']:
                    method_sig = f"- `{method['name']}("
                    if 'args' in method:
                        method_sig += ", ".join(method['args'])
                    method_sig += f") -> {method['returns']}`"
                    lines.append(method_sig)
                lines.append("")
            
            # Output events (if present)
            if 'output_events' in api_spec:
                lines.append("**Output Events:**")
                for event in api_spec['output_events']:
                    lines.append(f"- `{event}`")
                lines.append("")
            
            # Example
            if 'example' in api_spec:
                lines.append("**Example:**")
                lines.append("```python")
                lines.append(api_spec['example'].strip())
                lines.append("```")
                lines.append("")
            
            lines.append("---")
            lines.append("")
    
    # CLI Interface Section
    if 'cli_interface' in data:
        lines.extend([
            "## CLI Interface",
            ""
        ])
        
        for cmd_name, cmd_spec in data['cli_interface'].items():
            lines.append(f"### `{cmd_name}` Command")
            lines.append("")
            lines.append(f"**Description:** {cmd_spec['description']}")
            lines.append("")
            
            # Signature
            lines.append("**Usage:**")
            lines.append("```bash")
            lines.append(cmd_spec['signature'])
            lines.append("```")
            lines.append("")
            
            # Options
            if 'options' in cmd_spec:
                lines.append("**Options:**")
                for opt, desc in cmd_spec['options'].items():
                    lines.append(f"- `{opt}`: {desc}")
                lines.append("")
            
            # Behavior
            if 'behavior' in cmd_spec:
                lines.append("**Behavior:**")
                for line in cmd_spec['behavior'].strip().split('\n'):
                    lines.append(line)
                lines.append("")
            
            lines.append("---")
            lines.append("")
    
    # Internal Module APIs Section
    if 'internal_module_apis' in data:
        lines.extend([
            "## Internal Module APIs",
            ""
        ])
        
        for module_name, module_spec in data['internal_module_apis'].items():
            title = module_name.replace('_', ' ').title()
            lines.append(f"### {title}")
            lines.append("")
            
            # Output format
            if 'output_format' in module_spec:
                lines.append(f"**Output Format:** {module_spec['output_format']}")
                lines.append("")
            
            # Event schema
            if 'event_schema' in module_spec:
                lines.append("**Event Schema:**")
                lines.append("```yaml")
                for field, desc in module_spec['event_schema'].items():
                    lines.append(f"{field}: {desc}")
                lines.append("```")
                lines.append("")
            
            # Interface
            if 'interface' in module_spec:
                lines.append("**Interface:**")
                for method, sig in module_spec['interface'].items():
                    lines.append(f"- `{method}{sig}`")
                lines.append("")
            
            # Methods
            if 'methods' in module_spec:
                lines.append("**Methods:**")
                for method, sig in module_spec['methods'].items():
                    lines.append(f"- `{method}{sig}`")
                lines.append("")
            
            # Thread safety
            if 'thread_safety' in module_spec:
                lines.append(f"**Thread Safety:** {module_spec['thread_safety']}")
                lines.append("")
            
            # Rules (for analyzer)
            if 'rules' in module_spec:
                lines.append("**Bottleneck Detection Rules:**")
                for rule in module_spec['rules']:
                    lines.append(f"- {rule}")
                lines.append("")
            
            # Other properties
            for key in ['input', 'output', 'clock_sync_method', 'accuracy_target', 'output_formats']:
                if key in module_spec:
                    key_title = key.replace('_', ' ').title()
                    lines.append(f"**{key_title}:** {module_spec[key]}")
                    lines.append("")
            
            lines.append("---")
            lines.append("")
    
    # Configuration Section
    if 'configuration' in data:
        lines.extend([
            "## Configuration",
            ""
        ])
        
        config = data['configuration']
        
        # Environment variables
        if 'environment_variables' in config:
            lines.append("### Environment Variables")
            lines.append("")
            for var, desc in config['environment_variables'].items():
                lines.append(f"- `{var}`: {desc}")
            lines.append("")
        
        # Config file format
        if 'config_file_format' in config:
            lines.append(f"**Config File Format:** {config['config_file_format']}")
            lines.append("")
        
        # Precedence
        if 'precedence' in config:
            lines.append(f"**Precedence:** {config['precedence']}")
            lines.append("")
        
        lines.append("---")
        lines.append("")
    
    # Error Handling Section
    if 'error_handling' in data:
        lines.extend([
            "## Error Handling",
            "",
            "| Error | Collector Response | User Impact | Level |",
            "|-------|-------------------|-------------|-------|"
        ])
        
        for error, details in data['error_handling'].items():
            error_title = error.replace('_', ' ').title()
            response = details.get('collector_response', 'N/A')
            impact = details.get('user_impact', 'N/A')
            level = details.get('error_level', 'N/A')
            lines.append(f"| {error_title} | {response} | {impact} | {level} |")
        
        lines.append("")
    
    # Write to file
    output_path.write_text('\n'.join(lines) + '\n')
    print(f"✓ Generated {output_path} from {yaml_path}")


if __name__ == '__main__':
    # Paths relative to repository root
    repo_root = Path(__file__).parent.parent
    yaml_path = repo_root / 'Doc' / '3_module_design' / 'interfaces.yaml'
    output_path = repo_root / 'Doc' / '3_module_design' / 'ICD.md'
    
    if not yaml_path.exists():
        print(f"Error: {yaml_path} not found")
        exit(1)
    
    generate_icd(yaml_path, output_path)
